package de.tki.comfymodels.service.gateway;

import com.fasterxml.jackson.databind.JsonNode;

import java.io.File;
import java.util.List;
import java.util.concurrent.CompletableFuture;

/**
 * Unified Facade for all HTTP interactions with the ComfyUI backend server.
 */
public interface ComfyUiGateway {

    /**
     * Checks whether the ComfyUI server is reachable and active.
     */
    boolean isServerOnline();

    /**
     * Fetches the complete node specification registry (/object_info) dynamically from ComfyUI.
     */
    CompletableFuture<JsonNode> getObjectInfo();

    /**
     * Submits a workflow execution request to /prompt.
     *
     * @param promptPayload Complete JSON payload containing prompt graph
     * @return prompt_id generated by ComfyUI
     */
    CompletableFuture<String> submitPrompt(String promptPayload);

    /**
     * Uploads an input asset (image, audio, mask) to ComfyUI via /upload/image.
     */
    CompletableFuture<String> uploadAsset(File file);

    /**
     * Downloads an output asset from ComfyUI /view endpoint.
     */
    CompletableFuture<byte[]> downloadAsset(String filename, String subfolder, String type);

    /**
     * Retrieves prompt execution history from /history/{promptId}.
     */
    CompletableFuture<JsonNode> getHistory(String promptId);

    /**
     * Requests dynamic hot-reload of all model folders on the ComfyUI server.
     */
    CompletableFuture<Void> triggerModelRefresh();

    /**
     * Retrieves hardware and VRAM system statistics from /system_stats.
     */
    CompletableFuture<JsonNode> getSystemStats();

    /**
     * Dynamically determines input widget names for a given node class type using /object_info metadata.
     */
    List<String> getWidgetInputNames(String classType);
}
