package com.thomaskippster.comfyuicompanion.domain.llm;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Structured Output Schema for the Cognitive Router LLM.
 * The local LLM is instructed to strictly return JSON matching this POJO
 * to map user intentions to executable ComfyUI workflow components.
 */
@JsonIgnoreProperties(ignoreUnknown = true)
public class GenerationIntent {

    // E.g., "SDXL", "FLUX", "SD1.5"
    private String architecture;

    // The artistically enriched prompt generated by the LLM
    private String optimizedPositivePrompt;

    // e.g. "16:9", "1:1" (fixed the typo from targetAspectRation to targetAspectRatio)
    @JsonProperty("targetAspectRatio")
    private String targetAspectRatio;

    // True if wide-angle portraits or humans are requested
    private boolean requiresFaceDetailer;

    // True if textual elements (words/fonts) should be rendered in the image
    private boolean requiresTextRendering;

    // E.g., "juggernaut" or "anime"
    private String suggestedCheckpointKeyword;

    public String getArchitecture() {
        return architecture;
    }

    public void setArchitecture(String architecture) {
        this.architecture = architecture;
    }

    public String getOptimizedPositivePrompt() {
        return optimizedPositivePrompt;
    }

    public void setOptimizedPositivePrompt(String optimizedPositivePrompt) {
        this.optimizedPositivePrompt = optimizedPositivePrompt;
    }

    public String getTargetAspectRatio() {
        return targetAspectRatio;
    }

    public void setTargetAspectRatio(String targetAspectRatio) {
        this.targetAspectRatio = targetAspectRatio;
    }

    public boolean isRequiresFaceDetailer() {
        return requiresFaceDetailer;
    }

    public void setRequiresFaceDetailer(boolean requiresFaceDetailer) {
        this.requiresFaceDetailer = requiresFaceDetailer;
    }

    public boolean isRequiresTextRendering() {
        return requiresTextRendering;
    }

    public void setRequiresTextRendering(boolean requiresTextRendering) {
        this.requiresTextRendering = requiresTextRendering;
    }

    public String getSuggestedCheckpointKeyword() {
        return suggestedCheckpointKeyword;
    }

    public void setSuggestedCheckpointKeyword(String suggestedCheckpointKeyword) {
        this.suggestedCheckpointKeyword = suggestedCheckpointKeyword;
    }

    // True if high-resolution image is requested, triggering UltimateSDUpscale
    private boolean requiresUpscaling;

    public boolean isRequiresUpscaling() {
        return requiresUpscaling;
    }

    public void setRequiresUpscaling(boolean requiresUpscaling) {
        this.requiresUpscaling = requiresUpscaling;
    }
}
