import { useState, useEffect } from 'react'

function App() {
  const [prompt, setPrompt] = useState('')
  const [isLoading, setIsLoading] = useState(false)
  const [response, setResponse] = useState(null)
  const [error, setError] = useState(null)
  const [imageUrl, setImageUrl] = useState(null)
  const [statusMessage, setStatusMessage] = useState('System Ready')

  const pollStatus = async (promptId) => {
    try {
      const res = await fetch(`/api/v1/status/${promptId}`)
      if (res.ok) {
        const data = await res.json()
        if (data && data[promptId]) {
          // The job is done! ComfyUI returns the outputs in history
          const outputs = data[promptId].outputs;
          if (outputs) {
            // Find the image filename from SaveImage node output
            for (const key in outputs) {
              if (outputs[key].images && outputs[key].images.length > 0) {
                const filename = outputs[key].images[0].filename;
                setImageUrl(`/api/v1/image/${filename}`);
                setIsLoading(false);
                setStatusMessage('Image generation complete!');
                return;
              }
            }
          }
        }
      }
      
      // If not done, poll again after 2 seconds
      setTimeout(() => pollStatus(promptId), 2000);
    } catch (err) {
      console.error('Polling error', err);
      // Keep polling despite temporary network errors
      setTimeout(() => pollStatus(promptId), 2000);
    }
  }

  const handleSubmit = async (e) => {
    e.preventDefault()
    if (!prompt.trim()) return

    setIsLoading(true)
    setError(null)
    setResponse(null)
    setImageUrl(null)
    setStatusMessage('Orchestrating workflow and executing...')

    try {
      const res = await fetch('/api/v1/generate', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({ prompt }),
      })

      if (!res.ok) {
        throw new Error('Network response was not ok')
      }

      const data = await res.json()
      setResponse(data)
      
      if (data.promptId) {
        setStatusMessage('Waiting for ComfyUI generation...')
        pollStatus(data.promptId)
      } else {
        setIsLoading(false)
        setError('No promptId returned from backend.')
      }
    } catch (err) {
      setError(err.message)
      setIsLoading(false)
      setStatusMessage('Error occurred')
    }
  }

  return (
    <div className="app-container">
      <header className="header animate-fade-in">
        <h1>ComfyUI Companion</h1>
        <p>Intelligent Model Orchestration & Execution</p>
      </header>

      <div className="dashboard-panel glass-panel animate-fade-in" style={{ animationDelay: '0.1s' }}>
        <h2>Prompt Lab</h2>
        <form onSubmit={handleSubmit} className="input-group">
          <label htmlFor="promptInput">Describe your scene</label>
          <textarea 
            id="promptInput"
            value={prompt}
            onChange={(e) => setPrompt(e.target.value)}
            placeholder="e.g. A cinematic portrait of a man holding a cardboard sign that says 'Hallo'. Photorealistic."
            rows={4}
          />
          <button type="submit" disabled={isLoading} className={isLoading ? 'animate-pulse' : ''}>
            {isLoading ? 'Processing...' : 'Generate ✨'}
          </button>
        </form>

        <div className="status-bar">
          <div className={`status-indicator ${isLoading ? 'active' : error ? 'error' : ''}`}></div>
          <span>{statusMessage}</span>
        </div>
      </div>

      <div className="dashboard-panel glass-panel animate-fade-in" style={{ animationDelay: '0.2s' }}>
        <h2>Generated Asset</h2>
        {error && (
          <div style={{ color: 'var(--error-color)', padding: '16px', background: 'rgba(255,51,102,0.1)', borderRadius: '8px' }}>
            {error}
          </div>
        )}
        
        {!imageUrl && !isLoading && !error && (
          <p style={{ color: 'var(--text-muted)' }}>Submit a prompt to view the generated image.</p>
        )}

        {isLoading && !imageUrl && (
          <div style={{ display: 'flex', justifyContent: 'center', padding: '40px' }}>
            <div className="status-indicator active animate-pulse" style={{ width: '20px', height: '20px' }}></div>
          </div>
        )}

        {imageUrl && (
          <div className="input-group animate-fade-in" style={{ alignItems: 'center' }}>
            <img 
              src={imageUrl} 
              alt="Generated by ComfyUI" 
              style={{ maxWidth: '100%', borderRadius: '8px', boxShadow: '0 8px 32px 0 rgba(0,0,0,0.5)', border: '1px solid var(--glass-border)' }} 
            />
          </div>
        )}
      </div>
    </div>
  )
}

export default App
